# Generated by Django 2.2.7 on 2019-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sex',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
