# Generated by Django 2.2.7 on 2019-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0002_auto_20191113_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(choices=[(1500, '-woman'), (2000, '-man ~woman'), (2500, '~man +woman'), (3000, '+man')])),
                ('breakfast', models.CharField(max_length=500)),
                ('lunch', models.CharField(max_length=500)),
                ('snack', models.CharField(max_length=500)),
                ('dinner', models.CharField(max_length=500)),
            ],
        ),
    ]
