# Generated by Django 2.2.7 on 2019-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0003_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='calories',
            field=models.IntegerField(choices=[('-woman', '1500'), ('-man ~woman', '2000'), ('~man +woman', '2500'), ('+man', '3000')]),
        ),
    ]
