# Generated by Django 2.2.7 on 2019-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0005_auto_20191113_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
