# Generated by Django 2.2.7 on 2019-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0006_appuser_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='health',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
