# Generated by Django 2.1 on 2019-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigorit', '0007_appuser_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='bfcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='dinnercal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='lunchcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='snackcal',
            field=models.IntegerField(default=0),
        ),
    ]
